import React from 'react';
import { useStore } from '../../store';
import { Button, Badge } from '../ui';
import { Database, Download, Share2, Search } from 'lucide-react';

export const Sidebar: React.FC = () => {
  const { dataset, analysis, progress, progressStatus } = useStore();

  const handleDownload = () => {
    if (!analysis) return;

    const reportContent = `
NARRATIVE ANALYTICS REPORT
==========================

EXECUTIVE SUMMARY
-----------------
${analysis.narrativeBlock || 'No narrative summary available.'}

STRATEGIC INSIGHTS
------------------
${analysis.insights.map((ins, i) => `
[${i + 1}] ${ins.type}: ${ins.title}
Context: ${ins.context || 'N/A'}
Interpretation: ${ins.interpretation || 'N/A'}
Recommendation: ${ins.recommendation || 'N/A'}
`).join('\n')}

DATASET PROFILE
---------------
Total Records: ${dataset?.length.toLocaleString()}
Total Features: ${analysis.numericColumns.length}

GENERATED BY ARIA ANALYTICS
`.trim();

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `Narrative_Report_${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <aside className="w-[220px] bg-bg-1 border-r border-border flex flex-col p-4 overflow-y-auto gap-8">
      <section>
        <h4 className="text-[9px] font-bold text-text-muted uppercase tracking-[0.2em] mb-4 flex justify-between">
          Dataset <Database size={10} />
        </h4>
        <div className="bg-bg-2 border border-border p-3 rounded-sm space-y-2">
          <div className="flex justify-between text-[10px] font-mono">
            <span className="text-text-muted">Rows</span>
            <span className="text-text-primary">{dataset?.length.toLocaleString() || 0}</span>
          </div>
          <div className="flex justify-between text-[10px] font-mono">
            <span className="text-text-muted">Columns</span>
            <span className="text-text-primary">{analysis?.columns.length || 0}</span>
          </div>
          <div className="flex justify-between text-[10px] font-mono">
            <span className="text-text-muted">Features</span>
            <span className="text-text-primary">{analysis?.numericColumns.length || 0}</span>
          </div>
        </div>
      </section>

      <section className="flex-1 min-h-0 flex flex-col">
        <h4 className="text-[9px] font-bold text-text-muted uppercase tracking-[0.2em] mb-4 flex justify-between">
          Features <Search size={10} />
        </h4>
        <div className="flex-1 overflow-y-auto space-y-1 pr-1">
          {analysis?.columns.map(col => (
            <div key={col} className="flex items-center gap-2 px-2 py-1.5 hover:bg-bg-3 rounded-sm group cursor-pointer transition-colors">
              <Badge variant={analysis.numericColumns.includes(col) ? 'gold' : 'default'} className="!px-1 !py-0 !text-[7px]">
                {analysis.numericColumns.includes(col) ? 'NUM' : 'CAT'}
              </Badge>
              <span className="text-[10px] text-text-secondary group-hover:text-text-primary truncate font-mono">{col}</span>
            </div>
          ))}
        </div>
      </section>

      <section>
        <h4 className="text-[9px] font-bold text-text-muted uppercase tracking-[0.2em] mb-4 flex justify-between">
          Export <Share2 size={10} />
        </h4>
        <div className="space-y-2">
          <Button 
            variant="outline" 
            className="w-full" 
            icon={Download}
            onClick={handleDownload}
            disabled={!analysis}
          >
            Download Report
          </Button>
        </div>
      </section>

      <div className="mt-auto pt-4">
        <div className="flex justify-between text-[9px] font-bold mb-2">
          <span className="text-gold uppercase tracking-widest">{progressStatus}</span>
          <span className="text-text-muted">{progress}%</span>
        </div>
        <div className="h-0.5 bg-bg-4 w-full overflow-hidden">
          <div 
            className="h-full bg-gold shadow-[0_0_8px_var(--gold)] transition-all duration-500" 
            style={{ width: `${progress}%` }}
          ></div>
        </div>
      </div>
    </aside>
  );
};
