import React from 'react';
import { useStore } from '../../store';
import { Database, Download, Search, Share2 } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';

const featureItemVariants = {
  hidden:  { opacity: 0, x: -8 },
  visible: (i: number) => ({
    opacity: 1,
    x: 0,
    transition: { delay: i * 0.02, duration: 0.25, ease: 'easeOut' as const },
  }),
};

// Data crawl string (binary) duplicated for seamless loop
const CRAWL_TEXT = Array.from({ length: 60 }, (_, i) =>
  i % 7 === 0 ? '1' : i % 3 === 0 ? '0' : '1'
).join('\n');
const CRAWL_CONTENT = CRAWL_TEXT + '\n' + CRAWL_TEXT;

export const Sidebar: React.FC = () => {
  const { dataset, analysis, progress } = useStore();

  const handleDownload = () => {
    if (!analysis) return;

    const reportContent = `
NARRATIVE ANALYTICS REPORT
==========================

EXECUTIVE SUMMARY
-----------------
${analysis.narrativeBlock || 'No narrative summary available.'}

STRATEGIC INSIGHTS
------------------
${analysis.insights.map((ins, i) => `
[${i + 1}] ${ins.type}: ${ins.title}
Context: ${ins.context || 'N/A'}
Interpretation: ${ins.interpretation || 'N/A'}
Recommendation: ${ins.recommendation || 'N/A'}
`).join('\n')}

DATASET PROFILE
---------------
Total Records: ${dataset?.length.toLocaleString()}
Total Features: ${analysis.numericColumns.length}

GENERATED BY ARIA ANALYTICS
`.trim();

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url  = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `Narrative_Report_${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const isReady = progress === 100;
  const statusLabel = isReady
    ? 'ANALYSIS COMPLETE'
    : progress > 0 ? 'ANALYZING…' : 'READY';

  return (
    <aside
      className="w-[220px] flex flex-col p-4 overflow-hidden gap-6 flex-shrink-0 relative"
      style={{
        background: 'var(--bio-surface)',
        borderRight: '1px solid var(--bio-border)',
      }}
    >
      {/* Data crawl stream — right edge */}
      <div className="data-crawl-wrap">
        <div className="data-crawl-inner">{CRAWL_CONTENT}</div>
      </div>

      {/* ── Dataset Profile / CELL COUNT ── */}
      <section>
        <h4
          className="text-[9px] font-bold font-mono uppercase mb-3 flex justify-between items-center"
          style={{ color: 'rgba(57,255,106,0.4)', letterSpacing: '0.14em' }}
        >
          Your Data <Database size={9} style={{ color: 'rgba(57,255,106,0.3)' }} />
        </h4>
        <div
          className="p-3 rounded-lg space-y-2"
          style={{ background: 'var(--bio-card)', border: '1px solid var(--bio-border)' }}
        >
          {[
            { label: 'Entries',        value: dataset?.length.toLocaleString() || '—' },
            { label: 'Total Metrics',  value: analysis?.columns.length || '—' },
            { label: 'Number Metrics', value: analysis?.numericColumns.length || '—' },
          ].map(({ label, value }) => (
            <div key={label} className="flex justify-between text-[10px] font-mono">
              <span style={{ color: 'var(--text-muted)' }}>{label}</span>
              <span style={{ color: 'var(--bio-green)' }}>{value}</span>
            </div>
          ))}
        </div>
      </section>

      {/* ── Feature Catalog ── */}
      <section className="flex-1 min-h-0 flex flex-col">
        <h4
          className="text-[9px] font-bold font-mono uppercase mb-3 flex justify-between items-center flex-shrink-0"
          style={{ color: 'rgba(57,255,106,0.4)', letterSpacing: '0.14em' }}
        >
          Metric Catalog <Search size={9} style={{ color: 'rgba(57,255,106,0.3)' }} />
        </h4>
        <div className="flex-1 overflow-y-auto space-y-0.5 pr-1 custom-scrollbar">
          <AnimatePresence>
            {analysis?.columns.map((col, i) => {
              const isNum = analysis.numericColumns.includes(col);
              return (
                <motion.div
                  key={col}
                  custom={i}
                  variants={featureItemVariants}
                  initial="hidden"
                  animate="visible"
                  className="flex items-center gap-2 px-2 py-1.5 rounded-md group cursor-default transition-colors duration-150"
                  style={{ '--hover-bg': 'var(--bio-green-dim)' } as React.CSSProperties}
                  onMouseEnter={(e) => { (e.currentTarget as HTMLElement).style.background = 'var(--bio-green-dim)'; }}
                  onMouseLeave={(e) => { (e.currentTarget as HTMLElement).style.background = 'transparent'; }}
                >
                  {/* NUM / CAT badge */}
                  {isNum ? (
                    <span
                      className="text-[7px] font-bold font-mono uppercase px-1 py-0.5 rounded-sm border flex-shrink-0"
                      style={{
                        background: 'rgba(57,255,106,0.12)',
                        border: '1px solid rgba(57,255,106,0.25)',
                        color: 'var(--bio-green)',
                      }}
                    >
                      #
                    </span>
                  ) : (
                    <span
                      className="text-[7px] font-bold font-mono uppercase px-1 py-0.5 rounded-sm border flex-shrink-0"
                      style={{
                        background: 'rgba(180,79,255,0.10)',
                        border: '1px solid rgba(180,79,255,0.2)',
                        color: 'var(--bio-purple)',
                      }}
                    >
                      ABC
                    </span>
                  )}
                  <span
                    className="text-[10px] truncate font-mono"
                    style={{ color: 'rgba(57,255,106,0.6)' }}
                  >
                    {col}
                  </span>
                </motion.div>
              );
            })}
          </AnimatePresence>
        </div>
      </section>

      {/* ── Export ── */}
      <section>
        <h4
          className="text-[9px] font-bold font-mono uppercase mb-3 flex justify-between items-center"
          style={{ color: 'rgba(57,255,106,0.4)', letterSpacing: '0.14em' }}
        >
          Export <Share2 size={9} style={{ color: 'rgba(57,255,106,0.3)' }} />
        </h4>
        <motion.button
          whileHover={analysis ? { scale: 1.02 } : {}}
          whileTap={analysis ? { scale: 0.97 } : {}}
          transition={{ duration: 0.12 }}
          onClick={handleDownload}
          disabled={!analysis}
          className="w-full flex items-center justify-center gap-2 px-3 py-1.5 rounded-sm text-[11px] font-mono uppercase tracking-widest transition-all duration-200"
          style={{
            border: '1px solid var(--bio-border)',
            color: analysis ? 'var(--bio-green)' : 'rgba(57,255,106,0.25)',
            background: 'transparent',
            cursor: analysis ? 'pointer' : 'not-allowed',
            opacity: analysis ? 1 : 0.5,
          }}
          onMouseEnter={(e) => { if (analysis) (e.currentTarget as HTMLElement).style.background = 'var(--bio-green-dim)'; }}
          onMouseLeave={(e) => { (e.currentTarget as HTMLElement).style.background = 'transparent'; }}
        >
          <Download size={13} />
          Download Summary
        </motion.button>
      </section>

      {/* ── Engine Status Bar ── */}
      <div className="mt-auto pt-2" style={{ borderTop: '1px solid rgba(57,255,106,0.1)' }}>
        <div className="flex justify-between text-[9px] font-mono mb-2">
          <motion.span
            key={statusLabel}
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            className="uppercase tracking-widest font-bold"
            style={{ color: isReady ? 'var(--bio-teal)' : 'var(--bio-green)' }}
          >
            {statusLabel}
          </motion.span>
          <span style={{ color: 'var(--text-muted)' }}>{progress}%</span>
        </div>

        {/* Teal → Green gradient progress bar */}
        <div
          className="h-[2px] w-full overflow-hidden rounded-full"
          style={{ background: 'rgba(57,255,106,0.07)' }}
        >
          <motion.div
            className="h-full rounded-full"
            style={{
              background: 'linear-gradient(90deg, var(--bio-green), var(--bio-teal))',
              boxShadow: '0 0 8px rgba(57,255,106,0.5)',
            }}
            animate={{ width: `${progress}%` }}
            transition={{ duration: 0.6, ease: 'easeOut' }}
          />
        </div>
      </div>
    </aside>
  );
};
